name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.2.0
  - pyarrow=2.0  
  - jupyter=1.0.0
  - pydantic=1.8.2
  - matplotlib=3.7.3
  - pip:
      - wandb==0.15.11